apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-postgres
  template:
    metadata:
      labels:
        app: payment-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: payment_service
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: root
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              cpu: "3"
              memory: "4Gi"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "root"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "root"]
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: payment-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: payment-postgres
spec:
  selector:
    app: payment-postgres
  ports:
    - port: 5432
      targetPort: 5432
